import mongoose from "mongoose";

const saleSchema = new mongoose.Schema(
  {
    orderId: {
      type: String,
      required: [true, "Order ID is required"],
      unique: true,
      trim: true,
    },

    product: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Product",
      required: true,
    },

    color: {
      type: String,
      trim: true,
      default: null,
    },

    status: {
      type: String,
      enum: ["In progress", "Packed", "Delivered", "Returned", "Damaged"],
      default: "In progress",
    },

    // Whether an official bill/invoice has actually been issued.
    // Most Zeno orders can remain false.
    billIssued: {
      type: Boolean,
      default: false,
    },

    // Automatically generated by the backend when billIssued becomes true.
    // Never manually entered from the frontend.
    billNo: {
      type: String,
      trim: true,
      default: null,
    },

    // Useful for keeping an audit trail of when the bill was issued.
    billIssuedAt: {
      type: Date,
      default: null,
    },

    orderDate: {
      type: Date,
      default: Date.now,
    },

    quantity: {
      type: Number,
      required: true,
      min: 1,
    },

    unitPrice: {
      type: Number,
      required: [true, "Regular unit price is required"],
      min: 0,
    },

    lineTotal: {
      type: Number,
      required: [true, "Line total is required"],
      min: 0,
    },

    discount: {
      type: Number,
      default: 0,
      min: 0,
    },

    deliveryFeeCharged: {
      type: Number,
      default: null,
      min: 0,
    },

    deliveryCost: {
      type: Number,
      default: 0,
      min: 0,
    },

    deliveryPartner: {
      type: String,
      trim: true,
    },

    pointOfContact: {
      type: String,
      trim: true,
    },

    customerPhone: {
      type: String,
      trim: true,
      default: null,
    },

    notes: {
      type: String,
      trim: true,
    },

    paidStatus: {
      type: String,
      enum: ["Paid", "Unpaid", "COD"],
      default: "COD",
    },

    packagePhoto: {
      type: String,
      default: null,
    },

    packagedAt: {
      type: Date,
      default: null,
    },

    ocrText: {
      type: String,
      default: null,
    },

    ocrConfidence: {
      type: Number,
      default: null,
    },
  },
  { timestamps: true }
);

// Always derive discount from regular price vs actual charged amount.
saleSchema.pre("save", function (next) {
  const regular = (this.unitPrice || 0) * (this.quantity || 0);

  this.discount = Math.max(
    0,
    regular - (this.lineTotal || 0)
  );

  next();
});

saleSchema.index({ status: 1 });
saleSchema.index({ orderDate: -1 });
saleSchema.index({ billNo: 1 });

export default mongoose.model("Sale", saleSchema);